### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by mercadanteus** [Superice666/BlocklyNukkit#4]
I have a lot of errors like this, it virtually plagues my console:

https://hastebin.com/esudubixil.css

I think it causes big lag.  Could you look at it? thanks

**Comment by SuperIceCN** [comment]
> I have a lot of errors like this, it virtually plagues my console:
> 
> https://hastebin.com/esudubixil.css
> 
> I think it causes big lag. Could you look at it? thanks

@mercadanteus This error is caused by garbage collection. Nukkit wants to remove the chunk from memory, but blocklynukkit finds that there is a npc in the chunk and the npc will lead to a crash if this chunk is removed. And then blocklynukkit stops garbage collection and throw the error. Please offer your nukkitx version, and I think disabling auto-saving or GarbageCollection will help.

**Comment by SuperIceCN** [comment]
@mercadanteus I just make a new version to fix the bug, please download the new version and see if errors still come out , thx!
